@startuml
'https://plantuml.com/sequence-diagram

'---------- Config ----------------

autonumber

'---------- Header ----------------

boundary "Local Access Node" as lan

box "External Access Node"
  participant "DataNegotiationJob" as dnj
  participant "DataTransferJob" as dtj
  participant "DataVerificationJob" as dvj

end box

'---------- Diagram ----------------

dnj -> dtj++: syncData(DataNegotiationResult)
    dtj -> dtj: buildEntitiesToSyncRequest(DataNegotiationResult))
    dtj -> lan++: POST /sync/entities - Payload: EntitiesToSyncRequest
    return 200 OK - Payload: List<Entities>
    note right of lan
        List<Entities> is a list of ProductOffering
        and all related sub-entities, i.e.,
        ProductSpecification, ProductOfferingPrice,
        Catalog, etc.
    end note

    dtj -> dtj: verifyEntitiesIntegrity(List<Entities>, DataNegotiationResult)
    note right of dtj
        The integrity of the data is verified again with the hash.
    end note

    dtj -> dvj++: verifyData(List<Entities>)
    return

return

@enduml