@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam BoxPadding 10

' -------------------- Headers -------------------- '

actor "Operator" as operator

box "Local Access Node" #LightBlue
    control "P2PDataSyncController" as p2p_data_sync_controller_workflow
    control "Scheduler" as scheduler
    control "Bootstrapping" as bootstrapping
    participant "DataSyncWorkflow" as data_sync_workflow
end box

' -------------------- Diagram -------------------- '

note over operator, data_sync_workflow
    Trigger data sync
end note

alt "Bootstrapping"
    bootstrapping -> bootstrapping++: Application starts/restarts
    bootstrapping -> data_sync_workflow++: SyncData()
else "Scheduler"
    scheduler -> scheduler++: Cron job triggers
    scheduler -> data_sync_workflow: SyncData()
else "P2PDataSyncController"
    operator -> p2p_data_sync_controller_workflow++: GET /sync/data
    p2p_data_sync_controller_workflow -> data_sync_workflow: SyncData()
end

note over operator, data_sync_workflow
    Discovery
end note

@enduml
