@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam BoxPadding 10

' -------------------- Headers -------------------- '

actor "Operator" as operator

box "Local Access Node" #LightBlue
    participant "P2PDataSyncJob" as p2p_data_sync_job
    boundary "Context Broker" as context_broker
end box

boundary "External Access Node" as external_access_node

' -------------------- Diagram -------------------- '

activate p2p_data_sync_job

note over operator, external_access_node
    Sync
end note



loop forEach configured Access Node
    p2p_data_sync_job -> p2p_data_sync_job: Compare local_minimum_viable_entities_for_data_negotiation_list\n with external_minimum_viable_entities_for_data_negotiation_list
    p2p_data_sync_job -> external_access_node++: POST /sync/entities Payload: diff_entities_id_list
        note right of external_access_node
            This process is defined in
            the data_sync_retrieval
            diagram.
        end note
    return 201 Created Payload: entities_list
    p2p_data_sync_job -> context_broker: POST /ngsi-ld/v1/entityOperations/upsert Payload: entities_list
    return 201 Created
end

note over operator, external_access_node
    Completion
end note



@enduml
